# Generated by Django 5.1.1 on 2024-10-22 21:01

import django.core.validators
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_age_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.MinLengthValidator(2), profiles.validators.AlphaNumericValidator()]),
            preserve_default=False,
        ),
    ]
