# Generated by Django 5.1.1 on 2024-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='languages',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('c', 'C'), ('cpp', 'C++'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
